export const countryCode = [
  { value: '+86', name: '中国', local: '中国' },
  { value: '+001', name: '美国', local: 'United States' },
  { value: '+1', name: '加拿大', local: 'Canada' },
  { value: '+1242', name: '巴哈马', local: 'Bahamas' },
  { value: '+1246', name: '巴巴多斯', local: 'Barbados' },
  { value: '+1264', name: '安圭拉', local: 'Anguilla' },
  { value: '+1268', name: '安提瓜和巴布达', local: 'Antigua and Barbuda' },
  { value: '+1284', name: '英属维京群岛', local: 'British Virgin Islands' },
  { value: '+1340', name: '美属维京群岛', local: 'U.S. Virgin Islands' },
  { value: '+1345', name: '开曼群岛', local: 'Cayman Islands' },
  { value: '+1441', name: '百慕大', local: 'Bermuda' },
  { value: '+1473', name: '格林纳达', local: 'Grenada' },
  { value: '+1649', name: '特克斯和凯科斯群岛', local: 'Turks and Caicos Islands' },
  { value: '+1664', name: '蒙塞拉特', local: 'Montserrat' },
  { value: '+1670', name: '北马里亚纳群岛', local: 'Northern Mariana Islands' },
  { value: '+1671', name: '关岛', local: 'Guam' },
  { value: '+1684', name: '美属萨摩亚', local: 'American Samoa' },
  { value: '+1721', name: '荷属圣马丁', local: 'Sint Maarten' },
  { value: '+1758', name: '圣卢西亚', local: 'Saint Lucia' },
  { value: '+1767', name: '多米尼克', local: 'Dominica' },
  { value: '+1784', name: '圣文森特和格林纳丁斯', local: 'Saint Vincent and the Grenadines' },
  { value: '+1787', name: '波多黎各', local: 'Puerto Rico' },
  { value: '+1809', name: '多米尼加共和国', local: 'República Dominicana' },
  { value: '+1868', name: '特立尼达和多巴哥', local: 'Trinidad and Tobago' },
  { value: '+1869', name: '圣基茨和尼维斯', local: 'Saint Kitts and Nevis' },
  { value: '+1876', name: '牙买加', local: 'Jamaica' },
  { value: '+20', name: '埃及', local: '&#8235;مصر&#8236;' },
  { value: '+211', name: '南苏丹', local: '&#8235;جنوب السودان&#8236;' },
  { value: '+212', name: '摩洛哥', local: '&#8235;المغرب&#8236;' },
  { value: '+213', name: '阿尔及利亚', local: '&#8235;الجزائر&#8236;' },
  { value: '+216', name: '突尼斯', local: '&#8235;تونس&#8236;' },
  { value: '+218', name: '利比亚', local: '&#8235;ليبيا&#8236;' },
  { value: '+220', name: '冈比亚', local: 'Gambia' },
  { value: '+221', name: '塞内加尔', local: 'Sénégal' },
  { value: '+222', name: '毛里塔尼亚', local: '&#8235;موريتانيا&#8236;' },
  { value: '+223', name: '马里', local: 'Mali' },
  { value: '+224', name: '几内亚', local: 'Guinée' },
  { value: '+225', name: '科特迪瓦', local: 'Côte d’Ivoire' },
  { value: '+226', name: '布基纳法索', local: 'Burkina Faso' },
  { value: '+227', name: '尼日尔', local: 'Nijar' },
  { value: '+228', name: '多哥', local: 'Togo' },
  { value: '+229', name: '贝宁', local: 'Bénin' },
  { value: '+230', name: '毛里求斯', local: 'Moris' },
  { value: '+231', name: '利比里亚', local: 'Liberia' },
  { value: '+232', name: '塞拉利昂', local: 'Sierra Leone' },
  { value: '+233', name: '加纳', local: 'Gaana' },
  { value: '+234', name: '尼日利亚', local: 'Nigeria' },
  { value: '+235', name: '乍得', local: 'Tchad' },
  { value: '+236', name: '中非共和国', local: 'République centrafricaine' },
  { value: '+237', name: '喀麦隆', local: 'Cameroun' },
  { value: '+238', name: '佛得角', local: 'Kabu Verdi' },
  { value: '+239', name: '圣多美和普林西比', local: 'São Tomé e Príncipe' },
  { value: '+240', name: '赤道几内亚', local: 'Guinea Ecuatorial' },
  { value: '+241', name: '加蓬', local: 'Gabon' },
  { value: '+242', name: '刚果（布）', local: 'Congo-Brazzaville' },
  { value: '+243', name: '刚果（金）', local: 'Jamhuri ya Kidemokrasia ya Kongo' },
  { value: '+244', name: '安哥拉', local: 'Angola' },
  { value: '+245', name: '几内亚比绍', local: 'Guiné Bissau' },
  { value: '+246', name: '英属印度洋领地', local: 'British Indian Ocean Territory' },
  { value: '+247', name: '阿森松岛', local: 'Ascension Island' },
  { value: '+248', name: '塞舌尔', local: 'Seychelles' },
  { value: '+249', name: '苏丹', local: '&#8235;السودان&#8236;' },
  { value: '+250', name: '卢旺达', local: 'Rwanda' },
  { value: '+251', name: '埃塞俄比亚', local: 'Ethiopia' },
  { value: '+252', name: '索马里', local: 'Soomaaliya' },
  { value: '+253', name: '吉布提', local: 'Djibouti' },
  { value: '+254', name: '肯尼亚', local: 'Kenya' },
  { value: '+255', name: '坦桑尼亚', local: 'Tanzania' },
  { value: '+256', name: '乌干达', local: 'Uganda' },
  { value: '+257', name: '布隆迪', local: 'Uburundi' },
  { value: '+258', name: '莫桑比克', local: 'Moçambique' },
  { value: '+260', name: '赞比亚', local: 'Zambia' },
  { value: '+261', name: '马达加斯加', local: 'Madagasikara' },
  { value: '+262', name: '留尼汪', local: 'Réunion' },
  { value: '+263', name: '津巴布韦', local: 'Zimbabwe' },
  { value: '+264', name: '纳米比亚', local: 'Namibia' },
  { value: '+265', name: '马拉维', local: 'Malawi' },
  { value: '+266', name: '莱索托', local: 'Lesotho' },
  { value: '+267', name: '博茨瓦纳', local: 'Botswana' },
  { value: '+268', name: '斯威士兰', local: 'Swaziland' },
  { value: '+269', name: '科摩罗', local: '&#8235;جزر القمر&#8236;' },
  { value: '+27', name: '南非', local: 'South Africa' },
  { value: '+290', name: '圣赫勒拿', local: 'Saint Helena' },
  { value: '+291', name: '厄立特里亚', local: 'Eritrea' },
  { value: '+297', name: '阿鲁巴', local: 'Aruba' },
  { value: '+298', name: '法罗群岛', local: 'Føroyar' },
  { value: '+299', name: '格陵兰', local: 'Kalaallit Nunaat' },
  { value: '+30', name: '希腊', local: 'Ελλάδα' },
  { value: '+31', name: '荷兰', local: 'Nederland' },
  { value: '+32', name: '比利时', local: 'België' },
  { value: '+33', name: '法国', local: 'France' },
  { value: '+34', name: '西班牙', local: 'España' },
  { value: '+350', name: '直布罗陀', local: 'Gibraltar' },
  { value: '+351', name: '葡萄牙', local: 'Portugal' },
  { value: '+352', name: '卢森堡', local: 'Luxembourg' },
  { value: '+353', name: '爱尔兰', local: 'Ireland' },
  { value: '+354', name: '冰岛', local: 'Ísland' },
  { value: '+355', name: '阿尔巴尼亚', local: 'Shqipëria' },
  { value: '+356', name: '马耳他', local: 'Malta' },
  { value: '+357', name: '塞浦路斯', local: 'Κύπρος' },
  { value: '+358', name: '芬兰', local: 'Suomi' },
  { value: '+359', name: '保加利亚', local: 'България' },
  { value: '+36', name: '匈牙利', local: 'Magyarország' },
  { value: '+370', name: '立陶宛', local: 'Lietuva' },
  { value: '+371', name: '拉脱维亚', local: 'Latvija' },
  { value: '+372', name: '爱沙尼亚', local: 'Eesti' },
  { value: '+373', name: '摩尔多瓦', local: 'Republica Moldova' },
  { value: '+374', name: '亚美尼亚', local: 'Հայաստան' },
  { value: '+375', name: '白俄罗斯', local: 'Беларусь' },
  { value: '+376', name: '安道尔', local: 'Andorra' },
  { value: '+377', name: '摩纳哥', local: 'Monaco' },
  { value: '+378', name: '圣马力诺', local: 'San Marino' },
  { value: '+379', name: '梵蒂冈', local: 'Città del Vaticano' },
  { value: '+380', name: '乌克兰', local: 'Україна' },
  { value: '+381', name: '塞尔维亚', local: 'Србија' },
  { value: '+382', name: '黑山共和国', local: 'Crna Gora' },
  { value: '+385', name: '克罗地亚', local: 'Hrvatska' },
  { value: '+386', name: '斯洛文尼亚', local: 'Slovenija' },
  { value: '+387', name: '波斯尼亚和黑塞哥维那', local: 'Босна и Херцеговина' },
  { value: '+389', name: '马其顿', local: 'Македонија' },
  { value: '+39', name: '意大利', local: 'Italia' },
  { value: '+40', name: '罗马尼亚', local: 'România' },
  { value: '+41', name: '瑞士', local: 'Schweiz' },
  { value: '+420', name: '捷克共和国', local: 'Česká republika' },
  { value: '+421', name: '斯洛伐克', local: 'Slovensko' },
  { value: '+423', name: '列支敦士登', local: 'Liechtenstein' },
  { value: '+43', name: '奥地利', local: 'Österreich' },
  { value: '+44', name: '英国', local: 'United Kingdom' },
  { value: '+45', name: '丹麦', local: 'Danmark' },
  { value: '+46', name: '瑞典', local: 'Sverige' },
  { value: '+47', name: '挪威', local: 'Norge' },
  { value: '+48', name: '波兰', local: 'Polska' },
  { value: '+49', name: '德国', local: 'Deutschland' },
  { value: '+500', name: '福克兰群岛', local: 'Falkland Islands [Islas Malvinas]' },
  { value: '+501', name: '伯利兹', local: 'Belize' },
  { value: '+502', name: '危地马拉', local: 'Guatemala' },
  { value: '+503', name: '萨尔瓦多', local: 'El Salvador' },
  { value: '+504', name: '洪都拉斯', local: 'Honduras' },
  { value: '+505', name: '尼加拉瓜', local: 'Nicaragua' },
  { value: '+506', name: '哥斯达黎加', local: 'Costa Rica' },
  { value: '+507', name: '巴拿马', local: 'Panamá' },
  { value: '+508', name: '圣皮埃尔和密克隆群岛', local: 'Saint-Pierre-et-Miquelon' },
  { value: '+509', name: '海地', local: 'Haiti' },
  { value: '+51', name: '秘鲁', local: 'Perú' },
  { value: '+52', name: '墨西哥', local: 'México' },
  { value: '+53', name: '古巴', local: 'Cuba' },
  { value: '+54', name: '阿根廷', local: 'Argentina' },
  { value: '+55', name: '巴西', local: 'Brasil' },
  { value: '+56', name: '智利', local: 'Chile' },
  { value: '+57', name: '哥伦比亚', local: 'Colombia' },
  { value: '+58', name: '委内瑞拉', local: 'Venezuela' },
  { value: '+590', name: '法属圣马丁', local: 'Saint-Martin [partie française]' },
  { value: '+590', name: '瓜德罗普岛', local: 'Guadeloupe' },
  { value: '+590', name: '圣巴泰勒米', local: 'Saint-Barthélémy' },
  { value: '+591', name: '玻利维亚', local: 'Bolivia' },
  { value: '+592', name: '圭亚那', local: 'Guyana' },
  { value: '+593', name: '厄瓜多尔', local: 'Ecuador' },
  { value: '+594', name: '法属圭亚那', local: 'Guyane française' },
  { value: '+595', name: '巴拉圭', local: 'Paraguay' },
  { value: '+596', name: '马提尼克', local: 'Martinique' },
  { value: '+597', name: '苏里南', local: 'Suriname' },
  { value: '+598', name: '乌拉圭', local: 'Uruguay' },
  { value: '+599', name: '荷兰加勒比', local: 'Caribbean Netherlands' },
  { value: '+599', name: '库拉索', local: 'Curaçao' },
  { value: '+60', name: '马来西亚', local: 'Malaysia' },
  { value: '+61', name: '澳大利亚', local: 'Australia' },
  { value: '+62', name: '印度尼西亚', local: 'Indonesia' },
  { value: '+63', name: '菲律宾', local: 'Philippines' },
  { value: '+64', name: '新西兰', namlocale: 'New Zealand' },
  { value: '+65', name: '新加坡', local: 'Singapore' },
  { value: '+66', name: '泰国', local: 'ไทย' },
  { value: '+670', name: '东帝汶', local: 'Timor-Leste' },
  { value: '+6723', name: '诺福克岛', local: 'Norfolk Island' },
  { value: '+673', name: '文莱', local: 'Brunei' },
  { value: '+674', name: '瑙鲁', local: 'Nauru' },
  { value: '+675', name: '巴布亚新几内亚', local: 'Papua New Guinea' },
  { value: '+676', name: '汤加', local: 'Tonga' },
  { value: '+677', name: '所罗门群岛', local: 'Solomon Islands' },
  { value: '+678', name: '瓦努阿图', local: 'Vanuatu' },
  { value: '+679', name: '斐济', local: 'Fiji' },
  { value: '+680', name: '帕劳', local: 'Palau' },
  { value: '+681', name: '瓦利斯和富图纳', local: 'Wallis and Futuna' },
  { value: '+682', name: '库克群岛', local: 'Cook Islands' },
  { value: '+683', name: '纽埃', local: 'Niue' },
  { value: '+685', name: '萨摩亚', local: 'Samoa' },
  { value: '+686', name: '基里巴斯', local: 'Kiribati' },
  { value: '+687', name: '新喀里多尼亚', local: 'Nouvelle-Calédonie' },
  { value: '+688', name: '图瓦卢', local: 'Tuvalu' },
  { value: '+689', name: '法属波利尼西亚', local: 'Polynésie française' },
  { value: '+690', name: '托克劳', local: 'Tokelau' },
  { value: '+691', name: '密克罗尼西亚联邦', local: 'Micronesia' },
  { value: '+692', name: '马绍尔群岛', local: 'Marshall Islands' },
  { value: '+7', name: '俄罗斯', local: 'Россия' },
  { value: '+7', name: '哈萨克斯坦', local: 'Казахстан' },
  { value: '+81', name: '日本', local: '日本' },
  { value: '+82', name: '韩国', local: '대한민국' },
  { value: '+84', name: '越南', local: 'Việt Nam' },
  { value: '+850', name: '朝鲜', local: '조선 민주주의 인민 공화국' },
  { value: '+852', name: '香港', local: '香港' },
  { value: '+853', name: '澳门', local: '澳門' },
  { value: '+855', name: '柬埔寨', local: 'កម្ពុជា' },
  { value: '+856', name: '老挝', local: 'ສ.ປ.ປ ລາວ' },
  // { value: '+86', name: '中国', local: '中国' },
  { value: '+880', name: '孟加拉国', local: 'বাংলাদেশ' },
  { value: '+886', name: '台湾', local: '台灣' },
  { value: '+90', name: '土耳其', local: 'Türkiye' },
  { value: '+91', name: '印度', local: 'भारत' },
  { value: '+92', name: '巴基斯坦', local: '&#8235;پاکستان&#8236;' },
  { value: '+93', name: '阿富汗', local: '&#8235;افغانستان&#8236;' },
  { value: '+94', name: '斯里兰卡', local: 'ශ්&zwj;රී ලංකාව' },
  { value: '+95', name: '缅甸', local: 'မြန်မာ' },
  { value: '+960', name: '马尔代夫', local: 'Maldives' },
  { value: '+961', name: '黎巴嫩', local: '&#8235;لبنان&#8236;' },
  { value: '+962', name: '约旦', local: '&#8235;الأردن&#8236;' },
  { value: '+963', name: '叙利亚', local: '&#8235;سوريا&#8236;' },
  { value: '+964', name: '伊拉克', local: '&#8235;العراق&#8236;' },
  { value: '+965', name: '科威特', local: '&#8235;الكويت&#8236;' },
  { value: '+966', name: '沙特阿拉伯', local: '&#8235;المملكة العربية السعودية&#8236;' },
  { value: '+967', name: '也门', local: '&#8235;اليمن&#8236;' },
  { value: '+968', name: '阿曼', local: '&#8235;عُمان&#8236;' },
  { value: '+970', name: '巴勒斯坦', local: '&#8235;فلسطين&#8236;' },
  { value: '+971', name: '阿拉伯联合酋长国', local: '&#8235;الإمارات لعربية المتحدة&#8236;' },
  { value: '+972', name: '以色列', local: '&#8235;ישראל&#8236;' },
  { value: '+973', name: '巴林', local: '&#8235;البحرين&#8236;' },
  { value: '+974', name: '卡塔尔', local: '&#8235;قطر&#8236;' },
  { value: '+975', name: '不丹', local: 'འབྲུག' },
  { value: '+98', name: '伊朗', local: '&#8235;ایران&#8236;' },
  { value: '+992', name: '塔吉克斯坦', local: 'Tajikistan' },
  { value: '+993', name: '土库曼斯坦', local: 'Turkmenistan' },
  { value: '+994', name: '阿塞拜疆', local: 'Azərbaycan' },
  { value: '+995', name: '格鲁吉亚', local: 'საქართველო' },
  { value: '+996', name: '吉尔吉斯斯坦', local: 'Kyrgyzstan' },
  { value: '+998', name: '乌兹别克斯坦', local: 'Ўзбекистон' }
]
